# Generated by Django 2.2.3 on 2019-07-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamProfile',
            new_name='Team',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'FTVB_Agent'), (3, 'Ligue_Agent'), (4, 'Team'), (5, 'Player'), (5, 'Referee')], default=1),
        ),
    ]
