# Generated by Django 2.2.3 on 2019-07-12 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20190711_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Suspended', 'Suspended')], default='Inactive', max_length=100)),
                ('qualification_date', models.DateField(blank=True, null=True)),
                ('licence_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='users.Team')),
            ],
        ),
    ]
