# Generated by Django 2.2.3 on 2019-07-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teams', '0002_auto_20190712_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(upload_to='teams_players'),
        ),
        migrations.AlterField(
            model_name='player',
            name='proof',
            field=models.ImageField(upload_to='teams_players_proofs'),
        ),
    ]
