# Generated by Django 2.2.3 on 2019-07-14 14:34

import app_teams.Models.Player
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teams', '0003_auto_20190712_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='category',
            field=models.CharField(default='SG', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='sexe',
            field=models.CharField(default='M', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='licence_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(upload_to=app_teams.Models.Player.fileUploadPlayer),
        ),
        migrations.AlterField(
            model_name='player',
            name='proof',
            field=models.ImageField(upload_to=app_teams.Models.Player.fileUploadPlayer),
        ),
    ]
