# Generated by Django 2.2.3 on 2019-07-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teams', '0004_auto_20190714_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('Inactif', 'Inactif'), ('Actif', 'Actif'), ('Suspendu', 'Suspendu')], default='Inactif', max_length=100),
        ),
    ]
