# Generated by Django 2.2.3 on 2019-07-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_teams', '0005_auto_20190714_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='category',
        ),
    ]
